Fix the version of requests to avoid errors
[Details]
- RuntimeError: wda xctest launched but check failed
- This error is caused by the error that occurs in the following code.
  - https://github.com/openatx/facebook-wda/blob/1.4.7/wda/__init__.py#L350-L355
  - Error: HTTPConnection.request() got an unexpected keyword argument 'chunked'